name: Build and Release Go Binaries

on: 
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release Go Binaries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Build Go Binary
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o json-dup-keys-linux-amd64

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            json-dup-keys-linux-amd64
